title: change_world
author: suchang
email: 943420473@qq.com
description: > # this means to ignore newlines until "baseurl:"
* You can change everything here

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
